import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

import { fileURLToPath } from 'url';

// Read JSON data generated by read-tests.js
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const testDataPath = path.resolve(__dirname, 'test-data.json');
let testData = [];

if (fs.existsSync(testDataPath)) {
  const fileContent = fs.readFileSync(testDataPath, 'utf8');
  testData = JSON.parse(fileContent);
}

test.describe('Vibe Coding Dynamic Tests', () => {
  if (testData.length === 0) {
    test('No test data found', () => {
      console.log('test-data.json is empty or not found. Please run node read-tests.js first.');
      test.skip();
    });
    return;
  }

  testData.forEach((data, idx) => {
    test(`${data.testName || 'Unnamed Test'}_${idx}`, async ({ page }) => {
      // 1. Navigate to URL
      if (data.Url) {
        await page.goto(data.Url);
      } else {
        test.skip(true, 'No URL provided for this test case');
        return;
      }
      
      // 2. Perform Action (Click)
      if (data.Action === 'click' && data.Selector) {
        await page.locator(data.Selector).first().click();
      }
      
      // 3. Verify Element Visibility
      if (data.Action === 'verify_element' && data.Selector) {
        await expect(page.locator(data.Selector).first()).toBeVisible();
      }
      
      // 4. Verify Text inside Element
      if (data.Action === 'verify_text' && data.Selector && data.ExpectedValue) {
        await expect(page.locator(data.Selector).first()).toContainText(data.ExpectedValue);
      }
      
      // 5. Verify URL changed (if expectedUrl is provided)
      if (data.ExpectedUrl) {
        // Simple string match for URL path
        await expect(page).toHaveURL(new RegExp(data.ExpectedUrl));
      }
    });
});
  }
});
